# StoNED: MoM

In [1]:
import numpy as np

x = np.array([100,200,300,500,100,200,600,400,550,600])
y = np.array([75,100,300,400,25,50,400, 260, 180, 240])

In [2]:
from pystoned import *

In [3]:
# CNLS_prod_vrs

fun = "prod"
rts = "vrs"
cet = "addi"
model = CNLS.cnls(y, x, cet, fun, rts)

from pyomo.opt import SolverFactory
opt = SolverFactory('gams')
results = opt.solve(model, solver='mosek')

# retrive the residuals
val = list(model.e[:].value)
eps = np.asarray(val)

# decomposition by method od moment (MoM)
method      = 'MoM'
TE          = StoNED.stoned(y, eps, fun, method, cet)
TE

array([0.52223481, 0.69767821, 0.88587204, 0.92183461, 0.37283771,
       0.60011476, 0.92183461, 0.84775973, 0.74432569, 0.8141413 ])

In [4]:
# CNLS_cost_vrs

fun = "cost"
rts = "vrs"
cet = "addi"
model = CNLS.cnls(y, x, cet, fun, rts)

from pyomo.opt import SolverFactory
opt = SolverFactory('gams')
results = opt.solve(model, solver='mosek')

# retrive the residuals
val = list(model.e[:].value)
eps = np.asarray(val)

# decomposition by method od moment (MoM)
method      = 'MoM'
TE          = StoNED.stoned(y, eps, fun, method, cet)
TE

array([0.20710687, 0.60334524, 0.59026537, 0.73855704, 0.24512052,
       0.65255368, 0.81591139, 0.75955635, 0.90042088, 0.89816946])

In [5]:
# CNLS_prod_crs

fun = "prod"
rts = "crs"
cet = "mult"
model = CNLS.cnls(y, x, cet, fun, rts)

from pyomo.opt import SolverFactory
opt = SolverFactory('gams')
results = opt.solve(model, solver='minos')

# retrive the residuals
val = list(model.e[:].value)
eps = np.asarray(val)

# decomposition by method od moment (MoM)
method      = 'MoM'
TE          = StoNED.stoned(y, eps, fun, method, cet)
TE

array([0.79212675, 0.69887672, 0.8379623 , 0.80375889, 0.48703223,
       0.48703223, 0.76867622, 0.76324814, 0.57095522, 0.63391419])

In [6]:
# CNLS_cost_crs

fun = "cost"
rts = "crs"
cet = "mult"
model = CNLS.cnls(y, x, cet, fun, rts)

from pyomo.opt import SolverFactory
opt = SolverFactory('gams')
results = opt.solve(model, solver='minos')

# retrive the residuals
val = list(model.e[:].value)
eps = np.asarray(val)

# decomposition by method od moment (MoM)
method      = 'MoM'
TE          = StoNED.stoned(y, eps, fun, method, cet)
TE

array([0.97103604, 0.97188218, 0.97041571, 0.97089833, 0.97325513,
       0.97325513, 0.97128519, 0.97133838, 0.97273242, 0.97233413])